cs:

config:
	git config -l

count:
	ls -al | grep "RunWCDB.in"   | wc -l
	ls -al | grep "RunWCDB.out"  | wc -l
	ls -al | grep "TestWCDB.py"  | wc -l
	ls -al | grep "TestWCDB.out" | wc -l

log:
	git log

pull:
	git pull

status:
	git branch
	git remote
	git status
